---

- name: Update /etc/hosts
  lineinfile:
    path: /etc/hosts 
    line: "{{ hostvars[item].ansible_facts.eth1.ipv4.address }}  {{  hostvars[item].ansible_facts.hostname }}.example.com {{  hostvars[item].ansible_facts.hostname }}" 
  loop: "{{ groups['all'] }}"

#- name: Update hostnames
#  lineinfile:

- name: Start Firewalld service
  service:
    name: firewalld
    state: started
    enabled: true

- name: Enable http port on firewall
  firewalld:
    port: 80/tcp
    permanent: true
    state: enabled
    immediate: true
  
