---

- name: Update /etc/hosts
  lineinfile:
    path: /etc/hosts 
    line: "{{ hostvars[item].ansible_facts.eth1.ipv4.address }}  {{  hostvars[item].ansible_facts.hostname }}.example.com {{  hostvars[item].ansible_facts.hostname }}" 
  loop: "{{ groups['all'] }}"

#- name: Update hostnames
#  lineinfile:
  
